services:
  php:
    build: .
    container_name: my_php_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8
    container_name: my_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  nginx:
    image: nginx:latest
    container_name: my_nginx
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  mysql_data: